Fixing class def. not found errors: Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal Caused by: java.lang.NoClassDefFoundError: org/apache/http/config/Lookup By adding relevant dependencies in parent pom